# Generated by Django 2.0.8 on 2018-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0002_post_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no',
            field=models.IntegerField(),
        ),
    ]
