# Generated by Django 2.0.8 on 2018-08-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t', '0003_auto_20180824_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='no',
            field=models.IntegerField(default=True),
        ),
    ]
