# Generated by Django 2.1.5 on 2019-02-01 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='list',
            table=None,
        ),
    ]
