# Generated by Django 2.1.5 on 2019-02-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20190201_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='posts',
        ),
    ]
