# Generated by Django 2.1.5 on 2019-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190203_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='task',
            field=models.CharField(max_length=50),
        ),
    ]
